### ISSUE TITLE
**Members** [Filter]: Remove background on vertical scrollbars. Remove bottom scrollbar causing weird white box at bottom of dropdown

### ISSUE THREAD

**Issue by nhulz** [jplus-co/nevca#14]

**Comment by nhulz** [comment]
- [ ] Remove background on vertical scrollbars. 
- [ ] Remove bottom scrollbar causing weird white box at bottom of dropdown

<img width="1286" alt="screen shot 2017-11-05 at 8 07 08 pm" src="https://user-images.githubusercontent.com/7129206/32421296-ef98da6e-c264-11e7-8dee-30067fbe4279.png">

**Comment by mikehwagz** [comment]
I'm not seeing this in chrome or safari, but I believe `overflow: scroll` was the culprit. Should be set to `auto`

**Comment by nhulz** [comment]
Is it possible to remove the white background and just have it be the gray bar?
